// Code generated by mockery. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/b7777777v/fish_server/internal/biz/game"
	"github.com/stretchr/testify/mock"
)

// GameRecordRepo is a mock type for the game.GameRecordRepo interface
type GameRecordRepo struct {
	mock.Mock
}

// Create mocks the Create method
func (m *GameRecordRepo) Create(ctx context.Context, record *game.GameRecord) error {
	args := m.Called(ctx, record)
	return args.Error(0)
}

// Update mocks the Update method
func (m *GameRecordRepo) Update(ctx context.Context, record *game.GameRecord) error {
	args := m.Called(ctx, record)
	return args.Error(0)
}

// FindByID mocks the FindByID method
func (m *GameRecordRepo) FindByID(ctx context.Context, id int64) (*game.GameRecord, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*game.GameRecord), args.Error(1)
}

// FindByUserID mocks the FindByUserID method
func (m *GameRecordRepo) FindByUserID(ctx context.Context, userID int64, limit, offset int) ([]*game.GameRecord, error) {
	args := m.Called(ctx, userID, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*game.GameRecord), args.Error(1)
}

// FindBySessionID mocks the FindBySessionID method
func (m *GameRecordRepo) FindBySessionID(ctx context.Context, sessionID string) ([]*game.GameRecord, error) {
	args := m.Called(ctx, sessionID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*game.GameRecord), args.Error(1)
}

// FindActiveByUserID mocks the FindActiveByUserID method
func (m *GameRecordRepo) FindActiveByUserID(ctx context.Context, userID int64) (*game.GameRecord, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*game.GameRecord), args.Error(1)
}

// GetUserTotalStats mocks the GetUserTotalStats method
func (m *GameRecordRepo) GetUserTotalStats(ctx context.Context, userID int64) (*game.UserGameStats, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*game.UserGameStats), args.Error(1)
}
