# Docker環境配置文件
log:
  level: "debug" # 可選值: debug, info, warn, error
  format: "json" # 可選值: json, console

server:
  game:
    port: 9090
  admin:
    port: 6060

data:
  database:
    driver: "postgres"
    source: "postgresql://user:password@postgres:5432/fish_db?sslmode=disable"
  redis:
    addr: "redis:6379"
    password: ""
    db: 0

jwt:
  secret: "your-super-secret-key" # 務必修改成一個複雜的密鑰
  issuer: "fish_server" # token 發行者
  expire: 7200 # token 過期時間，單位為秒 (例如 7200 表示 2 小時)