version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: fish_db_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ../storage/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fish_db_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin:
    image: fish-server-admin:latest
    ports:
      - "6060:6060"
    environment:
      - ENVIRONMENT=dev
      - FISH_ENVIRONMENT=dev
      - LOG_LEVEL=debug
      - GIN_MODE=debug
    volumes:
      - ./config-docker.dev.yaml:/app/configs/config.yaml:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6060/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_dev_data: