// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/b7777777v/fish_server/internal/app/game"
	"github.com/b7777777v/fish_server/internal/biz/account"
	game2 "github.com/b7777777v/fish_server/internal/biz/game"
	"github.com/b7777777v/fish_server/internal/biz/player"
	"github.com/b7777777v/fish_server/internal/conf"
	"github.com/b7777777v/fish_server/internal/data"
	"github.com/b7777777v/fish_server/internal/pkg/logger"
	"github.com/b7777777v/fish_server/internal/pkg/token"
)

// Injectors from wire.go:

func initApp(config *conf.Config) (*game.GameApp, func(), error) {
	confData := config.Data
	log := config.Log
	v, cleanup, err := logger.NewLogger(log)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gameRepo := data.NewGameRepo(dataData, v)
	playerRepo := data.NewGamePlayerRepo(dataData, v)
	roomConfig := game2.NewDefaultRoomConfig()
	fishSpawner := game2.NewFishSpawner(v, roomConfig)
	mathModel := game2.NewMathModel(v)
	inMemoryInventoryRepo := data.NewInMemoryInventoryRepo(v)
	inventoryManager, err := game2.NewInventoryManager(inMemoryInventoryRepo, v)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rtpController := game2.NewRTPController(inventoryManager, v)
	roomManager := game2.NewRoomManager(v, fishSpawner, mathModel, inventoryManager, rtpController)
	gameUsecase := game2.NewGameUsecase(gameRepo, playerRepo, roomManager, fishSpawner, mathModel, inventoryManager, rtpController, v)
	client := data.ProvidePostgresClient(dataData)
	accountRepo := data.NewAccountRepo(client)
	jwt := config.JWT
	tokenHelper := token.NewTokenHelper(jwt)
	oAuthService := account.NewOAuthService()
	accountUsecase := account.NewAccountUsecase(accountRepo, tokenHelper, oAuthService)
	playerPlayerRepo := data.NewPlayerRepo(dataData, v)
	playerUsecase := player.NewPlayerUsecase(playerPlayerRepo, tokenHelper, v)
	hub := game.NewHub(gameUsecase, playerUsecase, v)
	webSocketHandler := game.NewWebSocketHandler(hub, tokenHelper, accountUsecase, v)
	messageHandler := game.NewMessageHandler(gameUsecase, hub, v)
	gameApp := game.NewGameApp(gameUsecase, accountUsecase, config, v, hub, webSocketHandler, messageHandler)
	return gameApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
