// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/b7777777v/fish_server/internal/app/admin"
	game2 "github.com/b7777777v/fish_server/internal/app/game"
	"github.com/b7777777v/fish_server/internal/biz/account"
	"github.com/b7777777v/fish_server/internal/biz/game"
	"github.com/b7777777v/fish_server/internal/biz/lobby"
	"github.com/b7777777v/fish_server/internal/biz/player"
	"github.com/b7777777v/fish_server/internal/biz/wallet"
	"github.com/b7777777v/fish_server/internal/conf"
	"github.com/b7777777v/fish_server/internal/data"
	"github.com/b7777777v/fish_server/internal/pkg/logger"
	"github.com/b7777777v/fish_server/internal/pkg/token"
)

// Injectors from wire.go:

// initApp 組裝完整的依賴圖，返回 AdminApp 實例
func initApp(config *conf.Config) (*admin.AdminApp, func(), error) {
	server := config.Server
	confData := config.Data
	log := config.Log
	v, cleanup, err := logger.NewLogger(log)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	playerRepo := data.NewPlayerRepo(dataData, v)
	jwt := config.JWT
	tokenHelper := token.NewTokenHelper(jwt)
	playerUsecase := player.NewPlayerUsecase(playerRepo, tokenHelper, v)
	walletRepo := data.NewWalletRepo(dataData, v)
	walletUsecase := wallet.NewWalletUsecase(walletRepo, v)
	gameRepo := data.NewGameRepo(dataData, v)
	gamePlayerRepo := data.NewGamePlayerRepo(dataData, v)
	roomConfig := game.NewDefaultRoomConfig()
	fishSpawner := game.NewFishSpawner(v, roomConfig)
	mathModel := game.NewMathModel(v)
	inMemoryInventoryRepo := data.NewInMemoryInventoryRepo(v)
	inventoryManager, err := game.NewInventoryManager(inMemoryInventoryRepo, v)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rtpController := game.NewRTPController(inventoryManager, v)
	roomManager := game.NewRoomManager(v, fishSpawner, mathModel, inventoryManager, rtpController)
	gameUsecase := game.NewGameUsecase(gameRepo, gamePlayerRepo, roomManager, fishSpawner, mathModel, inventoryManager, rtpController, v)
	client := data.ProvidePostgresClient(dataData)
	accountRepo := data.NewAccountRepo(client)
	oAuthService := account.NewOAuthService()
	accountUsecase := account.NewAccountUsecase(accountRepo, tokenHelper, oAuthService)
	hub := game2.NewHub(gameUsecase, playerUsecase, v)
	webSocketHandler := game2.NewWebSocketHandler(hub, tokenHelper, accountUsecase, v)
	messageHandler := game2.NewMessageHandler(gameUsecase, hub, v)
	gameApp := game2.NewGameApp(gameUsecase, accountUsecase, config, v, hub, webSocketHandler, messageHandler)
	redisClient := data.ProvideRedisClient(dataData)
	formationConfigRepo := data.NewFormationConfigRepo(client, redisClient, v)
	formationConfigService := game.NewFormationConfigService(formationConfigRepo, v)
	accountHandler := admin.NewAccountHandler(accountUsecase, tokenHelper)
	lobbyRepo := data.NewLobbyRepo(client)
	roomCache := data.NewRoomCache(redisClient)
	lobbyWalletRepo := data.NewLobbyWalletRepo(dataData, v)
	lobbyPlayerRepo := data.NewLobbyPlayerRepo(dataData, v)
	lobbyUsecase := lobby.NewLobbyUsecase(lobbyRepo, roomCache, lobbyWalletRepo, lobbyPlayerRepo)
	lobbyHandler := admin.NewLobbyHandler(lobbyUsecase, tokenHelper)
	adminService := admin.NewAdminService(playerUsecase, walletUsecase, gameApp, formationConfigService, tokenHelper, config, v, accountHandler, lobbyHandler)
	adminServer := admin.NewServer(server, adminService, v)
	adminApp := admin.NewAdminApp(adminServer, v)
	return adminApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
